version: 2.1
setup: true
orbs:
  go: circleci/go@1.7.3
  continuation: circleci/continuation@0.1.2
jobs:
  setup:
    executor: continuation/default
    steps:
      - run:
          name: Generate config
          # Generate dynamic configuration based on go.mod files
          command: |
            ../generate-config.sh > generated_config.yml
  build:
    machine:
      image: ubuntu-2204:current
    resource_class: large
    parallelism: 3
    steps:
      - checkout
      - go/install:
          version: 1.21.0
      - continuation/continue:
          configuration_path: generated_config.yml # use newly generated config to continue
      - store_test_results:
          path: .
      - run: curl -Os https://uploader.codecov.io/latest/linux/codecov && chmod +x codecov && ./codecov -t ${CODECOV_TOKEN}
